# The URL the site will be built for
base_url = "https://navalmintethos.github.io"

title = "Naval Mint Ethos"
description = "Ramblings on the Internet"

# generate rss feed
generate_feed = true

minify_html = true

# open external links in a new tab
external_links_target_blank = true

# try to guess correct punctiuation runes
smart_punctuation = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

default_language = "en"

taxonomies = [
  { name = "tags" },
]

[extra]
# Put all your custom variables here
author = "Valentin Thomas"
